-- Crear la tabla Deck
CREATE TABLE IF NOT EXISTS "Deck" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Crear la tabla Flashcard
CREATE TABLE IF NOT EXISTS "Flashcard" (
    id SERIAL PRIMARY KEY,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    "deckId" INTEGER NOT NULL REFERENCES "Deck"(id) ON DELETE CASCADE,
    difficulty INTEGER DEFAULT 2,
    "lastReviewed" TIMESTAMP WITH TIME ZONE,
    "nextReview" TIMESTAMP WITH TIME ZONE,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);