name: Branch Rules

on:
  pull_request:
    branches: ['main', 'develop']
  push:
    branches: ['*']

jobs:
  validate-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch name
        run: |
          echo "⚠️ Verificando reglas de branches..."
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          
          # Patrones permitidos
          VALID_PATTERNS="^(feature|bugfix|hotfix)/[a-zA-Z0-9/_-]+$|^(main|develop)$"
          
          if [[ ! $BRANCH_NAME =~ $VALID_PATTERNS ]]; then
            echo "❌ Las ramas deben seguir el patrón: feature/*, bugfix/*, hotfix/*"
            echo "❌ Rama actual: $BRANCH_NAME"
            exit 1
          fi
          
          echo "✅ Nombre de rama válido: $BRANCH_NAME"
